### ISSUE TITLE
Det er ikke muligt at vedhæfte billeder i webapp'en

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetBrugerflade#19]
Jeg kan i øjeblikket ikke vedhæfte billeder i webapp'en. 

Niels fra FRB bekræfter at samme ikke virker hos dem. Det virker i iphone og android app, men ikke i webapp.

Ring evt. for uddybende forklaring.

**Comment by runetvilum** [comment]
flyttet til [os2geo/RapportFraStedetApp/issues/39]
