### ISSUE TITLE
Select bliver blanke felter

### ISSUE THREAD

**Issue by Frederikssund** [os2geo/RapportFraStedetBrugerflade#4]
Hvis man i stedet for 'Radio' anvender 'Select' i opsætningen, så brugeren skal vælge ud fra en dropdown liste, bliver selve dropdown valglisten blank og med meget små bogstaver. Kun når man holder musen over linjerne kan man se valgmulighederne.

Fejlen er fundet på Chrome på PC.

**Comment by Frederikssund** [comment]
Kommentare fra Allan (syddjurs), der egentlig har indberettet fejlen:
Kan godt se select muligheden, men den virker heller ikke rigtigt på pc i Firefox og IE 9. Virker faktisk ok på Android og IOS, dog kan man ikke se den tekst der står som anvisning i feltet.

**Comment by runetvilum** [comment]
Testet i chrome, ios og android og virker ok.
kan forbedres i os2geo/RapportFraStedetMiniMap#9
