### ISSUE TITLE
Timestamp bliver ikke gemt.

### ISSUE THREAD

**Issue by agf-syddjurs** [os2geo/RapportFraStedetBrugerflade#7]
Har oprettet et string felt i db og udfyldt det med timestamp, men der bliver ikke fyldt noget i feltet, når der oprettes en indberetning.

**Comment by kjoller** [comment]
@agf-syddjurs, hos os virker det fint. I valideringsskemaet skal den sættes op som string med formatet date-time, og i brugerfladen skal det sættes op som type: timestamp.

**Comment by kjoller** [comment]
... Du er selvfølgelig velkommen til at få fat i mig :-)

**Comment by agf-syddjurs** [comment]
Hej Niels

Ok, havde fået at vide af Annette, at det bare skulle være et string felt i databasen, så det er der fejlen ligger. Så tak for svaret.

Venlig hilsen

Allan Gyldendal Frederiksen
GIS-koordinator
Syddjurs Kommune, Digitalisering

Direkte +4587535261
Mobil +4530924749
agf@syddjurs.dk

Fra: Niels Kjøller Hansen [mailto:notifications@github.com]
Sendt: 21. august 2015 11:30
Til: os2geo/RapportFraStedetBrugerflade
Cc: Allan Gyldendal Frederiksen
Emne: Re: [RapportFraStedetBrugerflade] Timestamp bliver ikke gemt. (#7)

@agf-syddjurshttps://github.com/agf-syddjurs, hos os virker det fint. I valideringsskemaet skal den sættes op som string med formatet date-time, og i brugerfladen skal det sættes op som type: timestamp.
